// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// S1cpp
double S1cpp(NumericVector x, NumericVector y);
RcppExport SEXP _RobustDC_S1cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(S1cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// S2cpp
double S2cpp(NumericVector x, NumericVector y);
RcppExport SEXP _RobustDC_S2cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(S2cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// S3cpp
double S3cpp(NumericVector x, NumericVector y);
RcppExport SEXP _RobustDC_S3cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(S3cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// S3ijk
arma::cube S3ijk(NumericVector x, NumericVector y);
RcppExport SEXP _RobustDC_S3ijk(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(S3ijk(x, y));
    return rcpp_result_gen;
END_RCPP
}
// U3xycpp
arma::vec U3xycpp(arma::mat comb_mat);
RcppExport SEXP _RobustDC_U3xycpp(SEXP comb_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type comb_mat(comb_matSEXP);
    rcpp_result_gen = Rcpp::wrap(U3xycpp(comb_mat));
    return rcpp_result_gen;
END_RCPP
}
// U3xcpp
arma::vec U3xcpp(arma::mat comb_mat);
RcppExport SEXP _RobustDC_U3xcpp(SEXP comb_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type comb_mat(comb_matSEXP);
    rcpp_result_gen = Rcpp::wrap(U3xcpp(comb_mat));
    return rcpp_result_gen;
END_RCPP
}
// U3ycpp
arma::vec U3ycpp(arma::mat comb_mat);
RcppExport SEXP _RobustDC_U3ycpp(SEXP comb_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type comb_mat(comb_matSEXP);
    rcpp_result_gen = Rcpp::wrap(U3ycpp(comb_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3xycpp
arma::vec S3xycpp(arma::mat index_mat, arma::mat x_mat, arma::mat y_mat);
RcppExport SEXP _RobustDC_S3xycpp(SEXP index_matSEXP, SEXP x_matSEXP, SEXP y_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3xycpp(index_mat, x_mat, y_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3xycpp_v2
arma::vec S3xycpp_v2(arma::mat index_mat, arma::mat x_mat, arma::mat y_mat);
RcppExport SEXP _RobustDC_S3xycpp_v2(SEXP index_matSEXP, SEXP x_matSEXP, SEXP y_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3xycpp_v2(index_mat, x_mat, y_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3xxcpp
arma::vec S3xxcpp(arma::mat index_mat, arma::mat x_mat);
RcppExport SEXP _RobustDC_S3xxcpp(SEXP index_matSEXP, SEXP x_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_mat(x_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3xxcpp(index_mat, x_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3xxcpp_v2
arma::vec S3xxcpp_v2(arma::mat index_mat, arma::mat x_mat);
RcppExport SEXP _RobustDC_S3xxcpp_v2(SEXP index_matSEXP, SEXP x_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_mat(x_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3xxcpp_v2(index_mat, x_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3yycpp
arma::vec S3yycpp(arma::mat index_mat, arma::mat y_mat);
RcppExport SEXP _RobustDC_S3yycpp(SEXP index_matSEXP, SEXP y_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3yycpp(index_mat, y_mat));
    return rcpp_result_gen;
END_RCPP
}
// S3yycpp_v2
arma::vec S3yycpp_v2(arma::mat index_mat, arma::mat y_mat);
RcppExport SEXP _RobustDC_S3yycpp_v2(SEXP index_matSEXP, SEXP y_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type index_mat(index_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    rcpp_result_gen = Rcpp::wrap(S3yycpp_v2(index_mat, y_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RobustDC_S1cpp", (DL_FUNC) &_RobustDC_S1cpp, 2},
    {"_RobustDC_S2cpp", (DL_FUNC) &_RobustDC_S2cpp, 2},
    {"_RobustDC_S3cpp", (DL_FUNC) &_RobustDC_S3cpp, 2},
    {"_RobustDC_S3ijk", (DL_FUNC) &_RobustDC_S3ijk, 2},
    {"_RobustDC_U3xycpp", (DL_FUNC) &_RobustDC_U3xycpp, 1},
    {"_RobustDC_U3xcpp", (DL_FUNC) &_RobustDC_U3xcpp, 1},
    {"_RobustDC_U3ycpp", (DL_FUNC) &_RobustDC_U3ycpp, 1},
    {"_RobustDC_S3xycpp", (DL_FUNC) &_RobustDC_S3xycpp, 3},
    {"_RobustDC_S3xycpp_v2", (DL_FUNC) &_RobustDC_S3xycpp_v2, 3},
    {"_RobustDC_S3xxcpp", (DL_FUNC) &_RobustDC_S3xxcpp, 2},
    {"_RobustDC_S3xxcpp_v2", (DL_FUNC) &_RobustDC_S3xxcpp_v2, 2},
    {"_RobustDC_S3yycpp", (DL_FUNC) &_RobustDC_S3yycpp, 2},
    {"_RobustDC_S3yycpp_v2", (DL_FUNC) &_RobustDC_S3yycpp_v2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RobustDC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
