# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S1cpp <- function(x, y) {
    .Call('_RobustDC_S1cpp', PACKAGE = 'RobustDC', x, y)
}

S2cpp <- function(x, y) {
    .Call('_RobustDC_S2cpp', PACKAGE = 'RobustDC', x, y)
}

S3cpp <- function(x, y) {
    .Call('_RobustDC_S3cpp', PACKAGE = 'RobustDC', x, y)
}

S3ijk <- function(x, y) {
    .Call('_RobustDC_S3ijk', PACKAGE = 'RobustDC', x, y)
}

U3xycpp <- function(comb_mat) {
    .Call('_RobustDC_U3xycpp', PACKAGE = 'RobustDC', comb_mat)
}

U3xcpp <- function(comb_mat) {
    .Call('_RobustDC_U3xcpp', PACKAGE = 'RobustDC', comb_mat)
}

U3ycpp <- function(comb_mat) {
    .Call('_RobustDC_U3ycpp', PACKAGE = 'RobustDC', comb_mat)
}

S3xycpp <- function(index_mat, x_mat, y_mat) {
    .Call('_RobustDC_S3xycpp', PACKAGE = 'RobustDC', index_mat, x_mat, y_mat)
}

S3xycpp_v2 <- function(index_mat, x_mat, y_mat) {
    .Call('_RobustDC_S3xycpp_v2', PACKAGE = 'RobustDC', index_mat, x_mat, y_mat)
}

S3xxcpp <- function(index_mat, x_mat) {
    .Call('_RobustDC_S3xxcpp', PACKAGE = 'RobustDC', index_mat, x_mat)
}

S3xxcpp_v2 <- function(index_mat, x_mat) {
    .Call('_RobustDC_S3xxcpp_v2', PACKAGE = 'RobustDC', index_mat, x_mat)
}

S3yycpp <- function(index_mat, y_mat) {
    .Call('_RobustDC_S3yycpp', PACKAGE = 'RobustDC', index_mat, y_mat)
}

S3yycpp_v2 <- function(index_mat, y_mat) {
    .Call('_RobustDC_S3yycpp_v2', PACKAGE = 'RobustDC', index_mat, y_mat)
}

